trigger:
- main
- master
- develop
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
 buildConfiguration:'Release'
 isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
stages:
- stage:'Build'
  jobs:
  - job: 'Build'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'ACRDocker'
          repository: '$(repository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            latest
            $(Build.BuildNumber)
