trigger:
- main
- master
- develop
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
  - job: 'Buildclient'
 displayname: 'Build job'

  steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'ACRDocker'
          repository: 'dotnetdemo-1'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
       
